export const USER_FIRST_NAME_MAX_LENGTH = 100;
export const USER_LAST_NAME_MAX_LENGTH = 100;
export const USER_EMAIL_MAX_LENGTH = 100;
export const USER_PASSWORD_MIN_LENGTH = 6;
export const USER_PASSWORD_MAX_LENGTH = 200;

export const LEDGER_NAME_MAX_LENGTH = 50;
export const LEDGER_DESCRIPTION_MAX_LENGTH = 200;

export const ENTRY_NARRATION_MAX_LENGTH = 200;
