exports.LEDGER_LIMIT = 20;
exports.ENTRY_LIMIT = 100;

exports.PER_MINUTE_REQUEST_LIMIT = 100;
exports.DEFAULT_PAGINATION_LIMIT = 10;

exports.USER_FIRST_NAME_MAX_LENGTH = 100;
exports.USER_MIDDLE_NAME_MAX_LENGTH = 100;
exports.USER_LAST_NAME_MAX_LENGTH = 100;
exports.USER_EMAIL_MAX_LENGTH = 100;
exports.USER_PASSWORD_MIN_LENGTH = 6;
exports.USER_PASSWORD_MAX_LENGTH = 200;
exports.USER_BIO_MAX_LENGTH = 200;
exports.USER_ORGANIZATION_MAX_LENGTH = 100;
exports.USER_JOB_TITLE_MAX_LENGTH = 100;
exports.USER_LOCATION_MAX_LENGTH = 200;

exports.LEDGER_NAME_MAX_LENGTH = 50;
exports.LEDGER_DESCRIPTION_MAX_LENGTH = 200;

exports.ENTRY_NARRATION_MAX_LENGTH = 200;
